# Generated by Django 4.2.16 on 2024-11-19 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('serial_number', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'repair',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('city_of_residence', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('apartment', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'worker',
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.IntegerField()),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.repair')),
            ],
            options={
                'db_table': 'spare_part',
            },
        ),
        migrations.CreateModel(
            name='RepairApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('planned_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('device_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.client')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.device')),
            ],
            options={
                'db_table': 'repair_application',
            },
        ),
        migrations.AddField(
            model_name='repair',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab_app.repairapplication'),
        ),
        migrations.CreateModel(
            name='EquipmentForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('device_serial_number', models.CharField(default='default_value', max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='lab_app.device')),
            ],
            options={
                'db_table': 'equipment_for_sale',
            },
        ),
        migrations.CreateModel(
            name='WorkerInRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.repair')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.worker')),
            ],
            options={
                'db_table': 'worker_in_repair',
                'unique_together': {('worker', 'repair')},
            },
        ),
    ]
